### ISSUE TITLE
Problems installing Batch Hillshader

### ISSUE THREAD

**Issue by dieza** [PANOimagen/batch_hillshader#2]
After a recent upgrade of the plugin, I’m unable to reinstall batch hillshader. Before this upgrade the plugin was working just fine.
Any ideas?
See the error report:

Couldn't load plugin 'batch_hillshader-master' due to an error when calling its classFactory() method 
ImportError: cannot import name '_ccallback_c' 

Traceback (most recent call last):
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 337, in startPlugin
 plugins[packageName] = package.classFactory(iface)
File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/batch_hillshader-master/__init__.py", line 47, in classFactory
 from .batch_hillshader import batchHillshader
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/batch_hillshader-master/batch_hillshader.py", line 49, in 
 from .batch_hillshader_dialog import batchHillshaderDialog
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/batch_hillshader-master/batch_hillshader_dialog.py", line 45, in 
 from . import hillshader_process
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/batch_hillshader-master/hillshader_process.py", line 42, in 
 from . import hillshade as hill
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Users/agus/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/batch_hillshader-master/hillshade.py", line 40, in 
 import scipy
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/__init__.py", line 119, in 
 from scipy._lib._ccallback import LowLevelCallable
File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 674, in _import
 mod = _builtin_import(name, globals, locals, fromlist, level)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/_lib/_ccallback.py", line 1, in 
 from . import _ccallback_c
ImportError: cannot import name '_ccallback_c'

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.2.2-Bonn Bonn, exported 
Python Path:

	• /Applications/QGIS3.app/Contents/MacOS/../Resources/python
	• /Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python
	• /Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
	• /Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
	• /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
	• /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
	• /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
	• /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
	• /Users/user/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by JaviBecerra** [comment]
Hi @dieza,
It seems that the problem lies within the scipy installation in your system. You should be able to reproduce the same error message launching a python console and typing:
`import scipy`
Try to reinstall scipy via pip, though it seems that other Mac users had to reinstall scipy via conda to get it working again.

**Comment by JaviBecerra** [comment]
Hi @dieza,
Did you get to fix this issue?

**Comment by dieza** [comment]
Yes, reinstalling scipy with `sudo pip3 install --upgrade scipy` did the trick in qgis 3.8.
So it works with scipy 1.3.0
